### ISSUE TITLE
issue with compile 

### ISSUE THREAD

**Issue by OriAlpha** [clariusdev/oem#1]
Thanks for this API module, but I tried to compile this and found that some libraries are missing.
Can you tell if there any pre-required libraries?

I have tried to compile with file example/console/MakeFile
**error given : cannot find -loem**

**Comment by clariusk** [comment]
this api is not yet released, the structure is provided as an outline for now

**Comment by OriAlpha** [comment]
Is there any time frame for releasing this soon

**Comment by clariusk** [comment]
please contact your local Clarius sales rep for more details
