### ISSUE TITLE
cusOemProbeInfo is not working 

### ISSUE THREAD

**Issue by tbjoern** [clariusdev/oem#7]
### Problem​
Calling  `cusOemProbeInfo` always returns -1
​The provided examples in the repository do not use this function either.
### Steps to reproduce
- Start the probe and connect to its wifi
- Run `cusOemInit` and `cusOemSetCert` -> The `ClariusCertFn` is called with `153`
- Connect to the probe -> The `ClariusConnectFn` is called with `0`
- Run `cusOemProbeInfo` -> return value is `-1`, struct contains no usable data

**Comment by clariusk** [comment]
cusOemLoadApplication() must be called successfully first for this function to work

**Comment by tbjoern** [comment]
I see. I tried it again and made a successful call to `cusOemLoadApplication("L7HD", "vascular")`. `cusOemProbeInfo` still returns -1. I do not get an `ClariusImagingFn` callback, so that might cause this issue. I think this is related to #5
